#
# This config-file is only needed for development. Instead of changing the url
# everytime you work locally on the project, you start both config-files, overwriting
# the first one with the development variables needed.
#
# Start development with › $ jekyll serve --config _config.yml,_config_dev.yml

url:  'http://localhost:4000'
baseurl: 	'/'
urlimg: 	'http://localhost:4000/images/'
description: 'We are OICRs passionate team of software engineers who build tools that help cancer researchers collaborate, work faster and take on more difficult challenges. This blog allows us to share information about or cutting-edge technology, groundbreaking tools and upcoming events.'

# See › https://github.com/jekyll/jekyll-gist#disabling-noscript-support
gist:
  noscript: false

sass:
  # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  style: :expanded
  line_numbers: true
  # trace_selectors: true
  # debug_info: true
  # FUTURE https://github.com/jekyll/jekyll-sass-converter/issues/12
  sourcemap: true

# Disable when not in production
google_analytics_tracking_id: false

# Gems
gems:
    - jekyll-asciidoc
    - jekyll-gist
    - jekyll-paginate

# Pagination
paginate: 5                      # Paginates all X entries
paginate_path: "blog/page:num"   # Pagination path › Important for blog page in /blog/ to work

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: "<!--more-->"
include: ['.htaccess']
